In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import warnings
warnings.filterwarnings('ignore')

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/twitter-entity-sentiment-analysis/twitter_validation.csv
/kaggle/input/twitter-entity-sentiment-analysis/twitter_training.csv


# Data loading and preprocessing

In [2]:
df_train= pd.read_csv("/kaggle/input/twitter-entity-sentiment-analysis/twitter_training.csv")

In [3]:
df_train

2401  Borderlands  Positive  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74676  9200       Nvidia  Positive   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   

      im getting on borderlands and i will murder you all ,  
0      I am coming to the borders and I will kill you...     
1      im getting on borderlands and i will kill you ...     
2      im coming on borderlands and i will murder you...     
3      im getting on borderlands 2 and i will murder ...     
4      im getting into borderlands and i can murder y...     
...                                                  ...     
74676  Just realized that the Windows partition of my...     
74677  Just realized that my Mac window partition is ...     
74678  Just realized the windows partition of my Mac ...     
74679  Just realized between the windows partition of...     
74680  Just like the windows partition of my Mac is l...     

[74681 rows x 4 columns]

**- Changeing columns name and shifting data in Zeroth row.**

In [4]:
current_col = df_train.columns.tolist()

df_train.loc[-1] = current_col
df_train.index = df_train.index+1
df_train = df_train.sort_index()

df_train.columns = ['tweet_id','entity','sentiment','text']

df_train.reset_index(drop=True,inplace=True)


In [5]:
df_train

tweet_id       entity sentiment  \
0         2401  Borderlands  Positive   
1         2401  Borderlands  Positive   
2         2401  Borderlands  Positive   
3         2401  Borderlands  Positive   
4         2401  Borderlands  Positive   
...        ...          ...       ...   
74677     9200       Nvidia  Positive   
74678     9200       Nvidia  Positive   
74679     9200       Nvidia  Positive   
74680     9200       Nvidia  Positive   
74681     9200       Nvidia  Positive   

                                                    text  
0      im getting on borderlands and i will murder yo...  
1      I am coming to the borders and I will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands 2 and i will murder ...  
...                                                  ...  
74677  Just realized that the Windows partition of my...  
74678  Just realized that my Mac window partition is ...  
74679  Just realized the windows partition of my Mac ...  
74680  Just realized between the windows partition of...  
74681  Just like the windows partition of my Mac is l...  

[74682 rows x 4 columns]

In [6]:
df_val = pd.read_csv('/kaggle/input/twitter-entity-sentiment-analysis/twitter_validation.csv')
df_val

3364             Facebook  Irrelevant  \
0     352               Amazon     Neutral   
1    8312            Microsoft    Negative   
2    4371                CS-GO    Negative   
3    4433               Google     Neutral   
4    6273                 FIFA    Negative   
..    ...                  ...         ...   
994  4891  GrandTheftAuto(GTA)  Irrelevant   
995  4359                CS-GO  Irrelevant   
996  2652          Borderlands    Positive   
997  8069            Microsoft    Positive   
998  6960      johnson&johnson     Neutral   

    I mentioned on Facebook that I was struggling for motivation to go for a run the other day, which has been translated by Tom’s great auntie as ‘Hayley can’t get out of bed’ and told to his grandma, who now thinks I’m a lazy, terrible person 🤣  
0    BBC News - Amazon boss Jeff Bezos rejects clai...                                                                                                                                                                                                  
1    @Microsoft Why do I pay for WORD when it funct...                                                                                                                                                                                                  
2    CSGO matchmaking is so full of closet hacking,...                                                                                                                                                                                                  
3    Now the President is slapping Americans in the...                                                                                                                                                                                                  
4    Hi @EAHelp I’ve had Madeleine McCann in my cel...                                                                                                                                                                                                  
..                                                 ...                                                                                                                                                                                                  
994  ⭐️ Toronto is the arts and culture capital of ...                                                                                                                                                                                                  
995  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...                                                                                                                                                                                                  
996  Today sucked so it’s time to drink wine n play...                                                                                                                                                                                                  
997  Bought a fraction of Microsoft today. Small wins.                                                                                                                                                                                                  
998  Johnson & Johnson to stop selling talc baby po...                                                                                                                                                                                                  

[999 rows x 4 columns]

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74682 entries, 0 to 74681
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   tweet_id   74682 non-null  object
 1   entity     74682 non-null  object
 2   sentiment  74682 non-null  object
 3   text       73996 non-null  object
dtypes: object(4)
memory usage: 2.3+ MB


In [8]:
df_train['text'] = df_train['text'].fillna('0')

In [9]:
df_train.isna().sum()

tweet_id     0
entity       0
sentiment    0
text         0
dtype: int64

In [10]:
current_col = df_val.columns.tolist()

df_val.loc[-1] = current_col
df_val.index = df_val.index+1
df_val = df_val.sort_index()

df_val.columns = ['tweet_id','entity','sentiment','text']

df_val.reset_index(drop=True,inplace=True)

In [11]:
df_val

tweet_id               entity   sentiment  \
0       3364             Facebook  Irrelevant   
1        352               Amazon     Neutral   
2       8312            Microsoft    Negative   
3       4371                CS-GO    Negative   
4       4433               Google     Neutral   
..       ...                  ...         ...   
995     4891  GrandTheftAuto(GTA)  Irrelevant   
996     4359                CS-GO  Irrelevant   
997     2652          Borderlands    Positive   
998     8069            Microsoft    Positive   
999     6960      johnson&johnson     Neutral   

                                                  text  
0    I mentioned on Facebook that I was struggling ...  
1    BBC News - Amazon boss Jeff Bezos rejects clai...  
2    @Microsoft Why do I pay for WORD when it funct...  
3    CSGO matchmaking is so full of closet hacking,...  
4    Now the President is slapping Americans in the...  
..                                                 ...  
995  ⭐️ Toronto is the arts and culture capital of ...  
996  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...  
997  Today sucked so it’s time to drink wine n play...  
998  Bought a fraction of Microsoft today. Small wins.  
999  Johnson & Johnson to stop selling talc baby po...  

[1000 rows x 4 columns]

# Bag of Words
> Applying bag of Word on df_train

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
cv = CountVectorizer()

In [14]:
bow = cv.fit_transform(df_train['text'])

* Conveting into vector.

In [15]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]


# Ngram

* Bi-gram, tri-gram and etc.

In [16]:
ncv = CountVectorizer(ngram_range=(5,5))

In [17]:
bow_ngram = ncv.fit_transform(df_train['text'])

In [18]:
print(len(ncv.vocabulary_))

709897


# TF-IDF

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(df_train['text']).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[ 7.42521722  6.95314961 10.27509762 ... 11.12239548 11.12239548
 11.12239548]
['00' '000' '00011' ... 'การออกอากาศของฉ' 'นจาก' 'ℐℓ٥']


In [22]:
tfidf.get_feature_names_out()

array(['00', '000', '00011', ..., 'การออกอากาศของฉ', 'นจาก', 'ℐℓ٥'],
      dtype=object)